coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "test_*.py"
  - "**/test_*.py"
  - "**/__pycache__/"
  - "**/node_modules/"
  - "src/desktop/src-tauri/target/"
  - "build/"
  - "dist/"

codecov:
  notify:
    after_n_builds: 3
    require_ci_to_pass: yes