codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 60..90

  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
