pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by >= 1"
      - "check-success = python-tests"
      - "check-success = frontend-tests"
      - "check-success = desktop-tests"
      - "base = main"
      - "label = automerge"
    actions:
      merge:
        method: merge
        commit_message: "+title +body"

  - name: Add automerge label when ready
    conditions:
      - "#approved-reviews-by >= 1"
      - "check-success = python-tests"
      - "check-success = frontend-tests"
      - "check-success = desktop-tests"
    actions:
      label:
        add:
          - ready-for-merge

  - name: Request review on draft PR
    conditions:
      - draft
    actions:
      comment:
        message: "This is a draft pull request. Remove draft status when ready for review."

  - name: Delete head branch after merge
    conditions:
      - merged
      - -base~1  # Not the first commit
    actions:
      delete_head_branch: {}

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request has merge conflicts. Please resolve them before merging."

  - name: Add size label
    conditions:
      - "-file(*.md)"  # Exclude documentation changes
      - "-file(*.txt)"  # Exclude text files
    actions:
      label:
        add:
          - "size/{{diff | size}}"

  - name: Welcome new contributors
    conditions:
      - author = first-time-contributor
    actions:
      comment:
        message: |
          Welcome! 👋 Thank you for your first contribution to Polylog6.
          
          Please make sure you've:
          - [ ] Read our contributing guidelines
          - [ ] Added tests for your changes
          - [ ] Updated documentation if needed
          
          We'll review your PR shortly!