/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/storage/symbols": {
    /**
     * Fetch symbol palette
     * @description Return a paginated list of symbols sourced from Tier 0 through Tier 4.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by tier (0 = Tier0, 1 = Tier1, 3 = Tier3, 4 = Tier4) */
          tier?: 0 | 1 | 3 | 4;
          /** @description Page number (zero-indexed) */
          page?: number;
          /** @description Page size (default 100) */
          limit?: number;
        };
      };
      responses: {
        /** @description List of symbols for the requested page */
        200: {
          content: {
            "application/json": components["schemas"]["SymbolList"];
          };
        };
      };
    };
  };
  "/api/storage/polyform/{symbol}": {
    /** Expand a symbol to full polyform data */
    get: {
      parameters: {
        path: {
          symbol: string;
        };
      };
      responses: {
        /** @description Expanded polyform data for the symbol */
        200: {
          content: {
            "application/json": components["schemas"]["ExpandedPolyform"];
          };
        };
        /** @description Symbol not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/api/storage/polyform": {
    /** Register a new polyform composition */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["NewPolyformRequest"];
        };
      };
      responses: {
        /** @description Polyform registered and symbol allocated */
        201: {
          content: {
            "application/json": components["schemas"]["ExpandedPolyform"];
          };
        };
      };
    };
  };
  "/api/storage/tier3-tier4/candidates": {
    /** Fetch promotion candidates for Tier 3 and Tier 4 */
    get: {
      responses: {
        /** @description Candidate list grouped by tier */
        200: {
          content: {
            "application/json": components["schemas"]["TierCandidateResponse"];
          };
        };
      };
    };
  };
  "/api/storage/stats": {
    /** Fetch storage and compression statistics */
    get: {
      responses: {
        /** @description Aggregate metrics for storage tiers */
        200: {
          content: {
            "application/json": components["schemas"]["StorageStats"];
          };
        };
      };
    };
  };
  "/api/detection/analyze_async": {
    /** Start asynchronous detection job */
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            image?: string;
            request_id?: string | null;
          };
        };
      };
      responses: {
        /** @description Job accepted for asynchronous processing */
        202: {
          content: {
            "application/json": components["schemas"]["JobStatus"];
          };
        };
      };
    };
  };
  "/api/detection/status/{job_id}": {
    /** Poll detection job status */
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      responses: {
        /** @description Status for the requested job */
        200: {
          content: {
            "application/json": components["schemas"]["JobStatus"];
          };
        };
        /** @description Job not found */
        404: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SymbolList: {
      symbols: components["schemas"]["SymbolSummary"][];
      /** @description Total number of symbols matching the filter */
      total: number;
      page: number;
      limit: number;
      /** @description Total number of pages */
      pages: number;
    };
    SymbolSummary: {
      symbol: string;
      tier: number;
      composition: string;
      /** @description Number of times observed/promoted */
      frequency?: number;
      metadata?: {
        [key: string]: unknown;
      };
    };
    ExpandedPolyform: {
      symbol: string;
      composition: string;
      geometry?: {
        [key: string]: unknown;
      };
      metrics?: {
        O?: number;
        I?: number;
        symmetry_score?: number;
        closure_ratio?: number;
        scaler_stability?: number;
        [key: string]: unknown;
      };
      tier: number;
      metadata?: {
        [key: string]: unknown;
      };
    };
    NewPolyformRequest: {
      /** @description Composition expressed in Tier 0 symbols (e.g., "a3+b2") */
      composition: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    TierCandidateResponse: {
      tier3: components["schemas"]["TierCandidate"][];
      tier4: components["schemas"]["TierCandidate"][];
    };
    TierCandidate: {
      symbol?: string;
      composition: string;
      metrics: {
        [key: string]: unknown;
      };
      frequency?: number;
      /** Format: date-time */
      last_seen_at?: string;
    };
    StorageStats: {
      tiers: {
        [key: string]: {
          count?: number;
          compression_ratio?: number;
          /** Format: date-time */
          last_updated?: string;
        };
      };
      totals: {
        symbols?: number;
        bytes_raw?: number;
        bytes_compressed?: number;
      };
      /** Format: date-time */
      recalculated_at?: string;
    };
    JobStatus: {
      job_id: string;
      /** @enum {string} */
      status: "pending" | "running" | "completed" | "failed";
      result?: Record<string, unknown> | null;
      error?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
